host: digital-land.github.io
show_govuk_logo: false
service_name: Planning Data
service_link: https://planning.data.gov.uk
phase: Beta
enable_search: yes
multipage_nav: true
collapsible_nav: true
max_toc_heading_level: 3
prevent_indexing: true
show_contribution_banner: false


# github_repo: digital-land/digital-land
# github_branch: main
# ga_tracking_id:
