@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include _styles.puml

HIDE_STEREOTYPE()

Person(user_data_provider, "Data Provider", "Prepares and publishes data.")
Person(user_planner, "Planner", "Browses the available datasets.")

System_Ext(app_data_provider, "Data Host", "Hosts data provider datasets")

SystemQueue(pipeline_collection, "Collection Pipeline", "Collects data from publishers, checking for errors and merging data before storing.")

System(app_main, "[[https://www.planning.data.gov.uk Application]]", "Main application presenting data to users in multiple formats.")
System(app_datasette_tiles, "[[https://datasette-tiles.planning.data.gov.uk Map Tile API]]", "Map tile server, serving vectors for use the main application user interface.")
System(app_datasette, "[[https://datasette.planning.data.gov.uk Data API]]", "Data server, responding to SQL queries from the main application.")

SystemDb(data_static_files, "[[https://files.planning.data.gov.uk/index.html Archive Storage]]", "Stores data from publishers making it available for sync with other applications.")

Rel_Down(user_data_provider, app_data_provider, "Publishes Data")

Rel_Left(pipeline_collection, app_data_provider, "Retrieves Data", "HTTPS")
Rel_Right(pipeline_collection, data_static_files, "Stores data", "HTTPS")

Rel_Up(data_static_files, app_datasette, "Sync SQLite files", "Lambda")
Rel_Up(data_static_files, app_datasette_tiles, "Sync map tile files", "ECS Task")
Rel_Up(data_static_files, app_main, "Sync live data", "ECS Task")

Rel_Left(app_main, app_datasette, "Requests data", "HTTPS")
Rel(user_planner, app_main, "Browses Data", "HTTPS")
Rel(user_planner, app_datasette_tiles, "Views Map Tiles", "HTTPS")
@enduml
